### ISSUE TITLE
[lagback] Block edge false positive [reopened]

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#122]
The carpet-block edge bug (#108 speed/fly fp) also exists for various other blocks!

Fixed 10.11.2016: 
* enchanting table
* All snow layers (even slow layer 1 that doesn't modify height)~~ (some snow layers do have one fly -.12 vl but don't setback)
* redstone (was no issue, it was just near other blocks with issue)
* cactus (don't know whether it was an issue or not, it was not in this list, but i build it)
* end portal
* end rod
* bed
* trapdoor
* slaps / Lower part of stairs
* repeater / comparators
* daylight detector
* soulsand

Still an issue:
* flower pots (Supergigant_Ring)
* chest (Janmm14)

I think these are all blocks where this issue occurrs, I went through the whole creative inventory.

**Comment by Photon-GitHub** [comment]
Soulsand is also not correctly working see #159 .

**Comment by konsolas** [comment]
Fixed and tested by Janmm14 for all the block types listed.

**Comment by Janmm14** [comment]
Chests are not fixed yet :/ https://www.youtube.com/watch?v=SjcuYv_w1Ps

Supergigant_Ring says, that flower pots are also not fixed.

**Comment by konsolas** [comment]
Fixed, confirmed by Rqcco and geNAZt

**Comment by Photon-GitHub** [comment]
Still there with enchantment tables and end portal frames

**Comment by konsolas** [comment]
Fixed.
