### ISSUE TITLE
mcMMO compatibility issues (FastBreak)

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1676]
mcMMO's Tree Feller & Leaf Blower are triggering kicks for FastBreak.
_(Plugin, and mcMMO build information below)_

Original report (detailed): https://ecocitycraft.com/forum/threads/bug-report-tree-feller-leaf-blower-malfunction.187172/

> Brief Description:
> When activated, Tree Feller fails to work (ie: doesn't explode trees - only removes the block you contact with your axe). Also, I have level 182 Woodcutting, so I can also use Leaf Blower (using your axe to quickly blow away remaining leaves). When activated, Leaf Blower works for a couple of leaf blocks and then I get kicked by Anti-Cheat.
> 
> Instructions (Tree Feller):
> 1. Initialize Tree Feller by r-clicking with your axe. I used an Eff5, Unbr3 diamond axe.
> 2. Activate Tree Feller by contacting a "log" block with the initialized axe.
> 3. Tree does not explode.
> 
> Instructions (Leaf Blower):
> 1. L-click tree leaves with your axe. I used an Eff5, Unbr3 diamond axe.
> 2. First leaf block or two "blow" away, as expected but third + leaf blocks not only don't blow away, they remain unbroken.

Everything in logs pertaining to "fastbreak" for the player in question on the day of.
https://gist.github.com/andrewkm/2da7c56ad1e2e91fb0fc49f98be6683f

CC: @nossr50 (tagging you here as we spoke on Discord)

### Core information
**Server version**: 1.13.2

**AAC version**: 4.0.6
**AAC config**: 4.0.5|1-Default-Celebrimbor
**AAC enabled checks**:

- Move (_kick thresholds disabled_)
- Timer
- BadPackets
- FastBreak
- FastPlace
- Interact

**ProtocolLib version**: 4.4.0 Build 425

**Plugin list**:
mcMMO Classic - 1.6.1 Build 66
Build server: https://ci.ecocitycraft.com/view/McMMO/job/McMMO-Classic/
_(Other plugins on request via Discord - andrewkm-0001)_

**Plugin information**:
mcMMO overhaul: 
https://www.spigotmc.org/resources/.64348/
https://github.com/mcMMO-Dev/mcMMO

mcMMO classic (**we use this**):
https://www.spigotmc.org/resources/.2445/
https://github.com/mcMMO-Dev/mcMMO-Classic

### Special environment information

**ViaVersion version**: 2.1.4 Build 361

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
AAC's mcMMO hook was removed in 4.0.x

4.1.x is set to have a new approach to compatibility with other plugins, but a custom hook may be needed for the time being.

**Comment by konsolas** [comment]
Do we know if there's been any progress on this, or if an alternate solution is necessary?

CC: @andrewkm @nossr50

**Comment by andrewkm** [comment]
@nossr50 is in the middle of an IRL move and said he’s going to be looking into it soon.

**Comment by andrewkm** [comment]
More information for @nossr50 when he is back.
It appears recently with some update to AAC (I'm not sure which) half the issue has been slightly improved.

Update...

> Tree Feller appears to be back in action for me, but Leaf Blower still only works for a half-dozen leaf blocks or so and then the leaves don't break any more. I am still kicked if I continue to try to break the leaves for an extended period.
> 
> Also, I've found that if I switch tools (in this case I switched to the /kit starter axe) I'm able to break leaves again for a while, but it eventually ends up with the same result.

Best course of action would be for mcMMO to make a fix for this ultimately.

**Comment by t00thpick1** [comment]
@konsolas What is the new approach you mentioned? Do we need to add something on our end?  If so, what sort of something.   I took a glance at your API docs on your spigot page but there doesn't seem to be much info in the PlayerViolation event to work with.

**Comment by CeIebrimbor** [comment]
The “new approach” was abandoned. Need to hook the good old fashioned way. Nossr has mentioned McMMO would listen for AAC, but I know he’s been busy of late.

**Comment by t00thpick1** [comment]
@CeIebrimbor So is the jist of it that I need to listen for the PlayerViolationEvent, somehow determine its caused by mcMMO then cancel it if so?  Or is there a better way to do it?

**Comment by konsolas** [comment]
That's pretty much it - cancel playerviolationevent if some mcMMO effect is active.

**Comment by konsolas** [comment]
If FastBreak is the only issue with classic, however, then ensuring that nothing fires BlockBreakEvent (FakeBlockBreakEvent is fine) will be sufficient.

**Comment by konsolas** [comment]
@andrewkm it may be useful to know if Leaf Blower is the **only** thing that doesn't work - has anything else come up in mcMMO that might be an issue?

**Comment by CeIebrimbor** [comment]
@konsolas Greenthumb used to be an issue back in the day with Interact. When using seeds to apply moss or grass to blocks. Something worth looking at if looking for conflicts.

**Comment by andrewkm** [comment]
@konsolas @nossr50 @t00thpick1 

Latest response from the bug report I got was:
It looks like leafblower is still broken.

> Thanks for staying with this - very frustrating.
> 
> Although Tree Feller seems to be back in action, Leaf Blower still yields the same result. I can break 5 to 10 leaves and then I just get the sound of leaves breaking, but they remain unbroken. Like before, if I continue to try, I get kicked from the game with the anti-cheat error code of 413. Same message as before.
> 
> Glad to have Tree Feller back though.

**Comment by CeIebrimbor** [comment]
Reported as fixed by users. Will reopen if further testing proves otherwise.

**Comment by andrewkm** [comment]
@celebrimbor this is not yet fixed.
LeafBlower causes the following:
https://gist.githubusercontent.com/andrewkm/175b72b2eaf900b0253749603fb05620/raw/3f70b7b15bcf6fa8cd0c0e4efeec7d421333bfe6/gistfile1.txt

**Comment by andrewkm** [comment]
Closing as it looks like all mcMMO issues have been solved.
