### ISSUE TITLE
Move FP when getting hit by mobs

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1707]
### Issue description
Happens especially when attacking something while sprinting (sprint+jump+attack)
https://gyazo.com/1fe1f5ae8ca7449afcbdcc185c7c7765 (From #1661)
### Core information
**Server version**: Spigot 1.14.4
**AAC version**: AAC v4.0.11-b1
**ProtocolLib version**: v4.5.0-SNAPSHOT
### Special environment information
**ViaVersion version**: n/a
**ProtocolSupport version**: n/a
**ViaBackwards version**: n/a
**BungeeCord plugins**: n/a
### Config
Default config

**Comment by Lysandr0** [comment]
I made a longer video that should better represent the issue.
https://www.dropbox.com/s/keokuxqyelggxp8/move-jumo%2Bsprint%2Battack.mov?dl=0
(I've also managed to get some really sporadic Criticals FPs)

**Comment by konsolas** [comment]
I'm going to assume that this particular issue was fixed at some point because I wasn't able to reproduce anything with a bunch of zombies, or 15 skeletons shooting at me.

**Comment by Lysandr0** [comment]
I still get false positives for some reasons, unfortunately. (default config)
At 04.10 you can also see a Critical fp.
https://www.dropbox.com/s/lzlvevjgr0v93oh/movefp%28jump%2Bsprint%2Battack%29.mov?dl=0

`[INFO] Plugins (9): LuckPerms, WorldEdit, Vault, Essentials, EssentialsSpawn, EssentialsChat, ProtocolLib, AAC, ConditionalCommands`

`[INFO] ProtocolLib v4.5.0-SNAPSHOT`

**Comment by konsolas** [comment]
Have you made any modifications to spigot perhaps?

**Comment by Lysandr0** [comment]
I haven’t touched nor updated the Spigot jar file.
It’s just a dummy server to test plugins out.

(Probably a major oversight on my part that might be related) The only modification I’ve made to the server was changing the Java version from _Java 8 - OpenJ9_ to _Java 8 - HotSpot_.
With 

With _Java 8 - OpenJ9_, the sever would fail to start-up whenever AAC attempted to inject into the PlayerConnection.class file.
(Relevant log: [Server.log](https://github.com/konsolas/AAC-Issues/files/3555177/Server.log))

On a localhost, the server would boot up just fine.

**Comment by konsolas** [comment]
4.1.8 makes some changes to how AAC handles entity bumping on 1.9+ servers. Do you think you could try it out?

**Comment by Lysandr0** [comment]
Tested. It seems to be more or less fixed now.
However, I feel feel like I should note that on my local server, with  AAC 4.1.7, I've only managed to get  just a few Move false positives.
Java infos:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by konsolas** [comment]
4.1.8
