### ISSUE TITLE
v3 Water fly bug

### ISSUE THREAD

**Issue by Camirlot** [konsolas/AAC-Issues#248]
https://youtu.be/FdBKRypCtw0

**Comment by konsolas** [comment]
Fixed.

**Comment by Rqcco** [comment]
This still exists at the edge of the water. https://www.youtube.com/watch?v=HABNo6TIlEM

**Comment by timr2000** [comment]
Still have problems with this..
