### ISSUE TITLE
v3 Stair detection

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#32]
https://vimeo.com/187911286

No kick, but watch until end. Would this trigger your underlying, global VL banding system? Eventually?

**Comment by CeIebrimbor** [comment]
Not sure this is worth tweaking unless it trips the global band system (if that still exists).

**Comment by konsolas** [comment]
The general band system has been removed, now it's just based on the displayed violation level.

Is sprinting up stairs worth checking?

**Comment by Photon-GitHub** [comment]
Well, there are some other legit moves and you can even be kicked because of them.
If you could join the test server I could show you some.

**Comment by CeIebrimbor** [comment]
With your VL culling rate for Speed seemingly being tripled, I don't see this being an issue. Just log spam with normal players producing verbose for simply running down stairs.

**Comment by konsolas** [comment]
New VL decrease rate for speed is 20/sec :)

**Comment by konsolas** [comment]
I'll want to sort out the log spam though

**Comment by Janmm14** [comment]
I do actually see every verbose message while using a vanilla client as a bug and overall leniency with such a vl decrement could probably cause issues later on when hack clients trigger one violation every 2 ticks (if they're not set back) they could easily speed up because of the high vl decrement.

Or do you have a system that prevents such things?

**Comment by konsolas** [comment]
Janmm14 is this your IGN? I can whitelist you on the test server.

**Comment by konsolas** [comment]
Fixed.

**Comment by Photon-GitHub** [comment]
Not fixed on the test server. Either recommended to reopen it or putting the new version on the test server.

**Comment by Photon-GitHub** [comment]
The stairs bug still exists on the test-server.

**Comment by Photon-GitHub** [comment]
Finally fixed.
