### ISSUE TITLE
v3 Slime Jump works

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#73]
When you use High Jump on Slime Blocks it bypasses. https://www.youtube.com/watch?v=dfOdlM4ogzo

**Comment by Photon-GitHub** [comment]
Probably this won't be fixed as the maths behind slimeblocks is pretty complicated and could throw a lot of false pos. Other bypasses / bugs are more important right now.

**Comment by Janmm14** [comment]
The simplest thing would be to not allow jumping higher than you were before touching slimes.

**Comment by Janmm14** [comment]
Isn't this more like a feature?

**Comment by konsolas** [comment]
Fixed, with proper checking for slime blocks.

**Comment by Rqcco** [comment]
This still exists, https://www.youtube.com/watch?v=AMekq8m1V0Q. Someone please reopen.

**Comment by Rqcco** [comment]
Seems Fixed.
