### ISSUE TITLE
When you respawn and the location is onground you often get sucked into the block

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#753]
You get a phase flag because the chunks are not loaded on the client. The server however does not seem to  setback correctly since the client is still stuck in the block and it needs to jump to get out of the block.

**Comment by CeIebrimbor** [comment]
Still on 3.2.1. Updating to Critical after the recent mass reduction of issue count.

**Comment by Janmm14** [comment]
Got this locally with 5+ blocks into the ground today.

**Comment by Toshka17** [comment]
Tell me please what kind of check it affects so that I can turn it off.

**Comment by Janmm14** [comment]
This one is caused by the check called "move", and it stops ALL other movement checks if turned off.

**Comment by Toshka17** [comment]
Players continue to fall through the blocks, especially when the thickness of the platform is 1 block

**Comment by Toshka17** [comment]
Min_vl option does not work in fly check.
Because if "teleport:" switch to false, then this bug will not occur. However, with min_vl = 80 and VL = 31 given to the player, the player will teleport down through the blocks.

**Comment by JuliCarles** [comment]
This happen in my server aswell.

**Comment by Janmm14** [comment]
debug logs would help here with AAC 3.3 or higher

**Comment by konsolas** [comment]
From @geNAZt 

![image](https://user-images.githubusercontent.com/9408210/29578744-4a6eda5c-8768-11e7-90bc-807bf4ee455d.png)

**Comment by Toshka17** [comment]
This was fixed in the new version 3.3.1 which is not yet available for everyone?

**Comment by Janmm14** [comment]
As far as I know  genazt meant it was fixed in one of the already public versions.

**Comment by Toshka17** [comment]
I'm using 3.2.2-b1 and this happens all the time.
I did not see that something was written about correcting this bug in the descriptions for the update for 3.3.0 and 3.3.0-b1

**Comment by JuliCarles** [comment]
It seems fixed in 3.3.0.
konsolas didn't say anything about it though.

**Comment by Janmm14** [comment]
Other fixes might have caused this to get fixed too accidentally.

**Comment by ludgart** [comment]
The problem is still here. I already disable the teleport down function in the fly settings. Im using the last aac version. Anyone have a solution?

**Comment by Janmm14** [comment]
Should be hopefully finally fixed fully in 3.3.4 in case it was not fixed before.
