### ISSUE TITLE
AAC blocking move packets

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#879]
### Issue description
AAC is blocking move packets.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.12

**AAC version**: 3.3.0-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: https://scr.hu/d5rMdy

### Special environment information
**ViaVersion version**: nope

**ProtocolSupport version**: b114

**ViaBackwards version**: nope

**BungeeCord plugins**: SkinsRestorer

### Configuration
Default, newest one.

**Comment by Xayanix** [comment]
Video: https://www.youtube.com/watch?v=sN9T788t0xI

**Comment by Janmm14** [comment]
Can you please show verbose messages when this happens?
Do one of these to get verbose messages:
* relevant log file portion you can find at `plugins/AAC/logs` 
* put `verbose:true` into at the end of the config without the `#` infront and give the accounts aac.verbose for testing

**Comment by Xayanix** [comment]
Indeed it is.
@konsolas please fix it, because i'm unable to use your plugin.

**Comment by Janmm14** [comment]
@Xayanix Please provide useful information like /aacdebug output when this happens to be able to see if it is the same cause.

**Comment by CeIebrimbor** [comment]
This is popping up for a few of my customers. No errors or unusual verbose goes with this. I am asking my clients to gather some if they can find it...

**Comment by SnakeDaoust1232** [comment]
I reported this a really long time ago. I believe the two are related: https://github.com/konsolas/AAC-Issues/issues/660

**Comment by PatoTheBest** [comment]
@CeIebrimbor 
Doesn't have to be a 1.8.8 server, it can be a 1.12 server, what matter is which version is the client using. Only the clients on version 1.8.X are affected though

**Comment by CeIebrimbor** [comment]
Good to know

**Comment by lucko** [comment]
Happening for me too when players teleport, seems to be fixed by disabling the fly check.

Relevant debug log:   
https://gist.github.com/lucko/eb6a983b8c3f4d34ee09a65a43813a1a

**Comment by rewtie** [comment]
Please fix this GAME BREAKING BUG @konsolas

**Comment by Janmm14** [comment]
Thanks for the debug log @lucko, it shows what happened there.
The client is not reacting to a sent teleportation, which usually even cheat clients do properly.

When a teleportation is occurring, AAC is ignoring all movements made until the client arrived exactly at the target location. This prevents false flags with lag on teleport.

As this does not seem to be an issue for many other big servers, I assume that it might be a problem related to certain servers and / or / cheat clients (maybe also some badly written legal modifications).

It would probably be a good idea to take a look at other plugins using ProtocolLib or other types of packet access like PacketListenerAPI.

**Comment by lucko** [comment]
> As this does not seem to be an issue for many other big servers, I assume that it might be a problem related to certain servers and / or / cheat clients (maybe also some badly written legal modifications).

I can reproduce it pretty consistently on our testing server, totally vanilla client.

Simply ask someone to login, and then teleport them to me and hit them. They are then sometimes 'ghosted', take no knockback, can't interact, etc.

This also occurs as part of AAC's fly check. When players get teleported down, those teleport events can also trigger the issue. (I have a debug log for that too, but it's pretty much identical to the one I posted above)

Not sure if it's config related, but we're using pretty much the default config, with a few changes to make it more lenient.

> It would probably be a good idea to take a look at other plugins using ProtocolLib or other types of packet access like PacketListenerAPI.

The only thing I can think of is ProtocolSupport. Other than that, I don't think we have any plugins which would mess with move packets at all.

I'm happy to provide any other logs / do more debugging etc.

**Comment by Xayanix** [comment]
@Janmm14 
It happens also on clean server, with only AAC & ProtocolLib...

**Comment by Janmm14** [comment]
@Xayanix @lucko 
I got it.

**Comment by konsolas** [comment]
@jordinjm's debug log: https://pastebin.com/ENWnEJqf

**Comment by konsolas** [comment]
The two debug logs show two different conditions which trigger this event. First, an absolute teleport to the exact same location as the player. Second, a relative teleport to a small offset. 

While these conditions can be corrected individually (and they will be in the next update), more debug logs are needed to determine if there are any other conditions which are problematic.

**Comment by konsolas** [comment]
@lucko can I have a few more details on how you reproduced that one? Managed to identify the problem for @jordinjm's debug log, but the client in your log seems to be ignoring the teleport completely.

**Comment by konsolas** [comment]
@Xayanix we'd love to have more information about your clean server. Worst case, please actually put the server jar on a file hosting site. 

Currently @Janmm14 can't reproduce with clean spigot 1.8.8.

**Comment by lucko** [comment]
@konsolas 
```
> about aac                                                                                                                                              │··
[12:23:45 INFO]: AAC version 3.3.0                                                                                                                       │··
[12:23:45 INFO]: AAC prevents and kicks suspected hackers from your server.                                                                              │··
[12:23:45 INFO]: Author: konsolas                                                                                                                        │··
> about ProtocolSupport                                                                                                                                  │··
[12:23:51 INFO]: ProtocolSupport version 4.27-dev                                                                                                        │··
[12:23:51 INFO]: Author: _Shevchik_                                                                                                                      │··
> about ProtocolLib                                                                                                                                      │··
[12:23:57 INFO]: ProtocolLib version 4.3.0                                                                                                               │··
[12:23:57 INFO]: Provides read/write access to the Minecraft protocol.                                                                                   │··
[12:23:57 INFO]: Authors: dmulloy2 and comphenix                                                                                                         │··
> version                                                                                                                                                │··
[12:24:03 INFO]: This server is running Paper version git-Paper-1190 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)                        │··
[12:24:03 INFO]: Checking version, please wait...                                                                                                        │··
[12:24:03 INFO]: You are 2 version(s) behind
```

It happens fairly frequently, I'd say affecting 20% of players, (just a guess) but it occurs naturally without having to try to reproduce it. 

We installed AAC across our servers on Friday and the issue was immediately obvious. Lots of complaints about players ghosting, as you'd expect.

We quickly disabled a lot of the movement/fly/interact/velocity related checks, which fixed the issue.

We then in recent days tried to reproduce the issue on our dev server.

Simply a case of asking someone to join, then teleporting them to yourself. Maybe 1/3 times you tried that, they'd end up being ghosted, and then take no KB, etc, which would continue until they re-logged.

You can see the server environment details above. The person in the log above was using a 1.8.8 client.

**Comment by Xayanix** [comment]
@lucko
+1

**Comment by lucko** [comment]
Turns out that (at least in our case) this issue was our fault - not AAC. :cry:

We had a plugin installed which throttled move packets. (kinda obvious, duh)    
https://github.com/vemacs/MoveFreq

Just to explain why we even had it in the first place, our instances often had 600+ players online at one time, and NCP was taking up a large proportion of the tick processing them. The plugin linked above reduced that by cancelling similar movement packets, and had no difference on the effectiveness of NCP or player experience. I appreciate AAC is vastly different, so I'm not surprised we had issues with it.

Sorry for wasting your time... :)

**Comment by jordinjm** [comment]
Please note that there is still an issue even though @lucko's issue is solved.

**Comment by Xayanix** [comment]
I will provide at night full debug of that issue with video included.

**Comment by Xayanix** [comment]
There it is.
Full server folder (remember to place AAC into plugins): https://www.mediafire.com/file/o9q9wj9unvhns3n/ACC_DEBUG.rar
Video how to reproduce: https://youtu.be/umZJUo6qJ0c

**Comment by lucko** [comment]
Even after removing the problematic plugin, we're still having issues with teleports.

This time when using ladders. Happens pretty consistently. Details about the server are posted above, the user in the following log was on 1.8.

https://paste.lucko.me/H45FqfaL83

**Comment by Xayanix** [comment]
@lucko because it is caused 100% by AAC.

**Comment by Janmm14** [comment]
@xayanix actually their plugin can create that issue really well too, debug log shows that stuff has improved a bit

**Comment by Xayanix** [comment]
OK, question is when @konsolas will take a look into it. I bought plugin almost one week ago and i'm still unable to use it, im wondering about make paypal refund...

**Comment by Janmm14** [comment]
@Xayanix An update is planned to be done in the next days, maybe also today.

**Comment by Xayanix** [comment]
I will be very happy if i could use this plugin today, thx.

**Comment by konsolas** [comment]
@lucko because you're using ProtocolSupport, you'll need to whitelist LADDER in the phase section of the config.

Currently investigating other possible causes of this.

**Comment by Xayanix** [comment]
And... any progress? :D

**Comment by PatoTheBest** [comment]
I've made some more tests
Server version: git-Paper-1104 (MC: 1.11.2)
AAC version: 3.3.0
ViaVersion: 1.2.0 on Bungeecord
ProtocolSupport: 4.25
ProtocolLib: 4.2.0

Me on 1.8
https://gist.github.com/PatoTheBest/c9398a4735e33bf93596f65c5b3343ce

A friend on 1.12
https://gist.github.com/PatoTheBest/daff470218d7d50ac963fa0109435292

Something I don't know is why my ping appears insanely high

**Comment by Janmm14** [comment]
@PatoTheBest
Your debug log does not show that you got teleported at all?!
And the debug log of your friend shows two successfull teleports.
Please note that AAC's debug mode does only allow debugging one player at a time.

**Comment by PatoTheBest** [comment]
@Janmm14 That's the problem, only happens on 1.8 clients. The other problem is that I get teleported clientsided and can move freely but on the server I'm not teleported

**Comment by Janmm14** [comment]
@PatoTheBest usually every attempt of the server to teleport you is listed there.

**Comment by Xayanix** [comment]
@Janmm14 When will ACC work? ...

**Comment by CeIebrimbor** [comment]
It works great in supported environments. ProtocolSupport has never been supported and is even listed on AAC's Overview as something that is not supported.

The fact that Konsolas has commented and also didn't close it means he is likely planning on fixing it. At some point...

Continuously bumping the issue each day with no new/relevant information is not getting this anywhere.

**Comment by konsolas** [comment]
All reproduced cases from valid debug logs were fixed in the 3.3.1 update (including relative teleports, absolute teleports to small offsets, and missed join packets).

However, the more general issue of ProtocolSupport has not been addressed.

**Comment by jordinjm** [comment]
I am still having an issue with relative teleports of any distance, here is a aac debug log: https://pastebin.com/b9kt78Gw

At line 455 (between ticks 2622 and 2623) you can see the teleport.

**Comment by jordinjm** [comment]
@CeIebrimbor This issue is NOT ONLY caused by ProtocolSupport, this issue is still prevalent in the current version of AAC on a server running only AAC and ProtocolLib. And this issue is CRITICAL because it causes the game to be unplayable if the server teleports you.

**Comment by PatoTheBest** [comment]
What server and client version are you using?

**Comment by Xayanix** [comment]
Nothing changed. Problem still exists.

**Comment by Xayanix** [comment]
Damn it, going to make a refund. Worthless plugin.

**Comment by CeIebrimbor** [comment]
Locking issue to collaborators and clearing _many_ pointless comments that have nothing to do with providing more information (just kicking and screaming).

**Comment by CeIebrimbor** [comment]
Confirmed still happening without ProtocolSupport on 3.3.1-b1 @konsolas 

Happens with all AAC and AACaddition checks disabled and even with all events cancelled with API. Only uninstalling AAC fixes the issue described.

**Comment by CeIebrimbor** [comment]
New video + Debug of video:
https://www.youtube.com/watch?v=eTTPXUDRVP4&feature=youtu.be
https://pastebin.com/v7jM6Y7M

**Comment by konsolas** [comment]
Update: This seems to be based on the client logged into the server.

blazingpack.pl is the suspect

**Comment by konsolas** [comment]
Lorak_ on discord has confirmed that a fix based on this worked, will be included in the next release.

**Comment by Janmm14** [comment]
Probably more fixes to this might be inside AAC 3.3.4
