### ISSUE TITLE
Hitting someone against a wall = Fly

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#945]
When you hit someone while they are against a wall, it flags for fly. Tested on the AAC test server.

**Comment by CeIebrimbor** [comment]
What is the highest VL you can obtain?

**Comment by Rerd** [comment]
https://hastebin.com/ozecosopub.sql
I can get infinite VL. The only thing changed with the fly config is the thresholds.
You can just join the test server and try it for yourself.

**Comment by CeIebrimbor** [comment]
Does it have to be a lifeless AFK player?

**Comment by Rerd** [comment]
For example, someone is playing pot pvp, and someone gets hit into a corner and is trapped there, they will then start getting flagged for fly and make it harder for them to play. This has been an issue for a while and I thought it would be known but I guess not.

**Comment by konsolas** [comment]
was fixed earlier

**Comment by Rerd** [comment]
Not fixed.

**Comment by konsolas** [comment]
Definitely is fixed. Check your test conditions.

**Comment by Rerd** [comment]
Again, not fixed.
[Debug](https://github.com/konsolas/AAC-Issues/files/1845765/debug.45a1a033-dab7-41d2-907c-130044882a6a.debug.log)
